DROP TABLE IF EXISTS users;
DROP INDEX IF EXISTS idx_email;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS roles_to_users;
DROP TABLE IF EXISTS permissioms_to_roles;